language: node_js
node_js:
  - '10'
stages:
  - name: lint and test

jobs:
  include:
    - stage: lint and test
      name: lint
      script:
        - lerna bootstrap
        - yarn lint
    - script:
        - lerna bootstrap
        - yarn test
      name: test
    - stage: deploy
      if: tag IS present
      name: deploy npm
      script:
        - lerna bootstrap
        - yarn build
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_API_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: 'yarn run publish'
        skip_cleanup: true
        on:
          node: '10'
          tags: true
    - stage: deploy
      if: tag IS present
      name: deploy docs
      script:
        - lerna bootstrap
        - lerna run build --scope yafl
      before_deploy:
        - git config --global user.name "${GITHUB_NAME}"
        - git config --global user.email "${GITHUB_EMAIL}"
        - echo "machine github.com login ${GITHUB_NAME} password ${GITHUB_TOKEN}" > ~/.netrc
      deploy:
        provider: script
        script: 'cd packages/docs && GIT_USER="${GITHUB_NAME}" yarn deploy'
        skip_cleanup: true
        on:
          node: '10'
          tags: true
        
          